### ISSUE TITLE
🧾course material page

### ISSUE THREAD

**Issue by abayo-luc** [abayo-luc/ikizamin-mobo#27]
# Tasks
- [ ] Display course content: text or video/images
- [ ] Play video with different options: pause, next, download
- [ ] Next & Back button
