### ISSUE TITLE
💸 Payment screen

### ISSUE THREAD

**Issue by abayo-luc** [abayo-luc/ikizamin-mobo#33]
# Tasks
 - [ ] Navigate to the payment screen
- [ ] Disply payment options
- [ ] Display payment card
